### ISSUE TITLE
Продажи должны храниться в массиве

### ISSUE THREAD

**Issue by coursar** [Furuzon/Cashback-DZ#3]
https://github.com/Furuzon/Cashback-DZ/blob/0eb2c344d52d3ee19c0f26c583ac1d153a6464f9/src/js/app.js#L6-L9

<img width="662" alt="Снимок экрана 2020-01-11 в 17 09 37" src="https://user-images.githubusercontent.com/3601892/72204090-057c6a80-3496-11ea-8990-78a7ac2f5a56.png">

**Comment by Furuzon** [comment]
Это исправленое ДЗ

**Comment by coursar** [comment]
Если сделали - нужно закрывать issue. Кроме того, issue надо закрывать сообщениями коммитов, а не руками.
